# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/rfaas

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/rfaas

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/rfaas/CMakeFiles /home/ubuntu/rfaas//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/rfaas/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rdmalib

# Build rule for target.
rdmalib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rdmalib
.PHONY : rdmalib

# fast build rule for target.
rdmalib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/build
.PHONY : rdmalib/fast

#=============================================================================
# Target rules for targets named rfaaslib

# Build rule for target.
rfaaslib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rfaaslib
.PHONY : rfaaslib

# fast build rule for target.
rfaaslib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rfaaslib.dir/build.make CMakeFiles/rfaaslib.dir/build
.PHONY : rfaaslib/fast

#=============================================================================
# Target rules for targets named executor

# Build rule for target.
executor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 executor
.PHONY : executor

# fast build rule for target.
executor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor.dir/build.make CMakeFiles/executor.dir/build
.PHONY : executor/fast

#=============================================================================
# Target rules for targets named executor_manager

# Build rule for target.
executor_manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 executor_manager
.PHONY : executor_manager

# fast build rule for target.
executor_manager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/build
.PHONY : executor_manager/fast

#=============================================================================
# Target rules for targets named resource_manager

# Build rule for target.
resource_manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 resource_manager
.PHONY : resource_manager

# fast build rule for target.
resource_manager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/build
.PHONY : resource_manager/fast

#=============================================================================
# Target rules for targets named benchmarks

# Build rule for target.
benchmarks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmarks
.PHONY : benchmarks

# fast build rule for target.
benchmarks/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmarks.dir/build.make CMakeFiles/benchmarks.dir/build
.PHONY : benchmarks/fast

#=============================================================================
# Target rules for targets named warm_benchmarker

# Build rule for target.
warm_benchmarker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 warm_benchmarker
.PHONY : warm_benchmarker

# fast build rule for target.
warm_benchmarker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warm_benchmarker.dir/build.make CMakeFiles/warm_benchmarker.dir/build
.PHONY : warm_benchmarker/fast

#=============================================================================
# Target rules for targets named parallel_invocations

# Build rule for target.
parallel_invocations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parallel_invocations
.PHONY : parallel_invocations

# fast build rule for target.
parallel_invocations/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_invocations.dir/build.make CMakeFiles/parallel_invocations.dir/build
.PHONY : parallel_invocations/fast

#=============================================================================
# Target rules for targets named cold_benchmarker

# Build rule for target.
cold_benchmarker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cold_benchmarker
.PHONY : cold_benchmarker

# fast build rule for target.
cold_benchmarker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cold_benchmarker.dir/build.make CMakeFiles/cold_benchmarker.dir/build
.PHONY : cold_benchmarker/fast

#=============================================================================
# Target rules for targets named cpp_interface

# Build rule for target.
cpp_interface: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp_interface
.PHONY : cpp_interface

# fast build rule for target.
cpp_interface/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_interface.dir/build.make CMakeFiles/cpp_interface.dir/build
.PHONY : cpp_interface/fast

#=============================================================================
# Target rules for targets named functions

# Build rule for target.
functions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 functions
.PHONY : functions

# fast build rule for target.
functions/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/functions.dir/build.make CMakeFiles/functions.dir/build
.PHONY : functions/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f _deps/spdlog-build/CMakeFiles/spdlog.dir/build.make _deps/spdlog-build/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

benchmarks/cold_benchmark.o: benchmarks/cold_benchmark.cpp.o
.PHONY : benchmarks/cold_benchmark.o

# target to build an object file
benchmarks/cold_benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cold_benchmarker.dir/build.make CMakeFiles/cold_benchmarker.dir/benchmarks/cold_benchmark.cpp.o
.PHONY : benchmarks/cold_benchmark.cpp.o

benchmarks/cold_benchmark.i: benchmarks/cold_benchmark.cpp.i
.PHONY : benchmarks/cold_benchmark.i

# target to preprocess a source file
benchmarks/cold_benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cold_benchmarker.dir/build.make CMakeFiles/cold_benchmarker.dir/benchmarks/cold_benchmark.cpp.i
.PHONY : benchmarks/cold_benchmark.cpp.i

benchmarks/cold_benchmark.s: benchmarks/cold_benchmark.cpp.s
.PHONY : benchmarks/cold_benchmark.s

# target to generate assembly for a file
benchmarks/cold_benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cold_benchmarker.dir/build.make CMakeFiles/cold_benchmarker.dir/benchmarks/cold_benchmark.cpp.s
.PHONY : benchmarks/cold_benchmark.cpp.s

benchmarks/cold_benchmark_opts.o: benchmarks/cold_benchmark_opts.cpp.o
.PHONY : benchmarks/cold_benchmark_opts.o

# target to build an object file
benchmarks/cold_benchmark_opts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cold_benchmarker.dir/build.make CMakeFiles/cold_benchmarker.dir/benchmarks/cold_benchmark_opts.cpp.o
.PHONY : benchmarks/cold_benchmark_opts.cpp.o

benchmarks/cold_benchmark_opts.i: benchmarks/cold_benchmark_opts.cpp.i
.PHONY : benchmarks/cold_benchmark_opts.i

# target to preprocess a source file
benchmarks/cold_benchmark_opts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cold_benchmarker.dir/build.make CMakeFiles/cold_benchmarker.dir/benchmarks/cold_benchmark_opts.cpp.i
.PHONY : benchmarks/cold_benchmark_opts.cpp.i

benchmarks/cold_benchmark_opts.s: benchmarks/cold_benchmark_opts.cpp.s
.PHONY : benchmarks/cold_benchmark_opts.s

# target to generate assembly for a file
benchmarks/cold_benchmark_opts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cold_benchmarker.dir/build.make CMakeFiles/cold_benchmarker.dir/benchmarks/cold_benchmark_opts.cpp.s
.PHONY : benchmarks/cold_benchmark_opts.cpp.s

benchmarks/cpp_interface.o: benchmarks/cpp_interface.cpp.o
.PHONY : benchmarks/cpp_interface.o

# target to build an object file
benchmarks/cpp_interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_interface.dir/build.make CMakeFiles/cpp_interface.dir/benchmarks/cpp_interface.cpp.o
.PHONY : benchmarks/cpp_interface.cpp.o

benchmarks/cpp_interface.i: benchmarks/cpp_interface.cpp.i
.PHONY : benchmarks/cpp_interface.i

# target to preprocess a source file
benchmarks/cpp_interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_interface.dir/build.make CMakeFiles/cpp_interface.dir/benchmarks/cpp_interface.cpp.i
.PHONY : benchmarks/cpp_interface.cpp.i

benchmarks/cpp_interface.s: benchmarks/cpp_interface.cpp.s
.PHONY : benchmarks/cpp_interface.s

# target to generate assembly for a file
benchmarks/cpp_interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_interface.dir/build.make CMakeFiles/cpp_interface.dir/benchmarks/cpp_interface.cpp.s
.PHONY : benchmarks/cpp_interface.cpp.s

benchmarks/cpp_interface_opts.o: benchmarks/cpp_interface_opts.cpp.o
.PHONY : benchmarks/cpp_interface_opts.o

# target to build an object file
benchmarks/cpp_interface_opts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_interface.dir/build.make CMakeFiles/cpp_interface.dir/benchmarks/cpp_interface_opts.cpp.o
.PHONY : benchmarks/cpp_interface_opts.cpp.o

benchmarks/cpp_interface_opts.i: benchmarks/cpp_interface_opts.cpp.i
.PHONY : benchmarks/cpp_interface_opts.i

# target to preprocess a source file
benchmarks/cpp_interface_opts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_interface.dir/build.make CMakeFiles/cpp_interface.dir/benchmarks/cpp_interface_opts.cpp.i
.PHONY : benchmarks/cpp_interface_opts.cpp.i

benchmarks/cpp_interface_opts.s: benchmarks/cpp_interface_opts.cpp.s
.PHONY : benchmarks/cpp_interface_opts.s

# target to generate assembly for a file
benchmarks/cpp_interface_opts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_interface.dir/build.make CMakeFiles/cpp_interface.dir/benchmarks/cpp_interface_opts.cpp.s
.PHONY : benchmarks/cpp_interface_opts.cpp.s

benchmarks/parallel_invocations.o: benchmarks/parallel_invocations.cpp.o
.PHONY : benchmarks/parallel_invocations.o

# target to build an object file
benchmarks/parallel_invocations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_invocations.dir/build.make CMakeFiles/parallel_invocations.dir/benchmarks/parallel_invocations.cpp.o
.PHONY : benchmarks/parallel_invocations.cpp.o

benchmarks/parallel_invocations.i: benchmarks/parallel_invocations.cpp.i
.PHONY : benchmarks/parallel_invocations.i

# target to preprocess a source file
benchmarks/parallel_invocations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_invocations.dir/build.make CMakeFiles/parallel_invocations.dir/benchmarks/parallel_invocations.cpp.i
.PHONY : benchmarks/parallel_invocations.cpp.i

benchmarks/parallel_invocations.s: benchmarks/parallel_invocations.cpp.s
.PHONY : benchmarks/parallel_invocations.s

# target to generate assembly for a file
benchmarks/parallel_invocations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_invocations.dir/build.make CMakeFiles/parallel_invocations.dir/benchmarks/parallel_invocations.cpp.s
.PHONY : benchmarks/parallel_invocations.cpp.s

benchmarks/parallel_invocations_opts.o: benchmarks/parallel_invocations_opts.cpp.o
.PHONY : benchmarks/parallel_invocations_opts.o

# target to build an object file
benchmarks/parallel_invocations_opts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_invocations.dir/build.make CMakeFiles/parallel_invocations.dir/benchmarks/parallel_invocations_opts.cpp.o
.PHONY : benchmarks/parallel_invocations_opts.cpp.o

benchmarks/parallel_invocations_opts.i: benchmarks/parallel_invocations_opts.cpp.i
.PHONY : benchmarks/parallel_invocations_opts.i

# target to preprocess a source file
benchmarks/parallel_invocations_opts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_invocations.dir/build.make CMakeFiles/parallel_invocations.dir/benchmarks/parallel_invocations_opts.cpp.i
.PHONY : benchmarks/parallel_invocations_opts.cpp.i

benchmarks/parallel_invocations_opts.s: benchmarks/parallel_invocations_opts.cpp.s
.PHONY : benchmarks/parallel_invocations_opts.s

# target to generate assembly for a file
benchmarks/parallel_invocations_opts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parallel_invocations.dir/build.make CMakeFiles/parallel_invocations.dir/benchmarks/parallel_invocations_opts.cpp.s
.PHONY : benchmarks/parallel_invocations_opts.cpp.s

benchmarks/settings.o: benchmarks/settings.cpp.o
.PHONY : benchmarks/settings.o

# target to build an object file
benchmarks/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmarks.dir/build.make CMakeFiles/benchmarks.dir/benchmarks/settings.cpp.o
.PHONY : benchmarks/settings.cpp.o

benchmarks/settings.i: benchmarks/settings.cpp.i
.PHONY : benchmarks/settings.i

# target to preprocess a source file
benchmarks/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmarks.dir/build.make CMakeFiles/benchmarks.dir/benchmarks/settings.cpp.i
.PHONY : benchmarks/settings.cpp.i

benchmarks/settings.s: benchmarks/settings.cpp.s
.PHONY : benchmarks/settings.s

# target to generate assembly for a file
benchmarks/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmarks.dir/build.make CMakeFiles/benchmarks.dir/benchmarks/settings.cpp.s
.PHONY : benchmarks/settings.cpp.s

benchmarks/warm_benchmark.o: benchmarks/warm_benchmark.cpp.o
.PHONY : benchmarks/warm_benchmark.o

# target to build an object file
benchmarks/warm_benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warm_benchmarker.dir/build.make CMakeFiles/warm_benchmarker.dir/benchmarks/warm_benchmark.cpp.o
.PHONY : benchmarks/warm_benchmark.cpp.o

benchmarks/warm_benchmark.i: benchmarks/warm_benchmark.cpp.i
.PHONY : benchmarks/warm_benchmark.i

# target to preprocess a source file
benchmarks/warm_benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warm_benchmarker.dir/build.make CMakeFiles/warm_benchmarker.dir/benchmarks/warm_benchmark.cpp.i
.PHONY : benchmarks/warm_benchmark.cpp.i

benchmarks/warm_benchmark.s: benchmarks/warm_benchmark.cpp.s
.PHONY : benchmarks/warm_benchmark.s

# target to generate assembly for a file
benchmarks/warm_benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warm_benchmarker.dir/build.make CMakeFiles/warm_benchmarker.dir/benchmarks/warm_benchmark.cpp.s
.PHONY : benchmarks/warm_benchmark.cpp.s

benchmarks/warm_benchmark_opts.o: benchmarks/warm_benchmark_opts.cpp.o
.PHONY : benchmarks/warm_benchmark_opts.o

# target to build an object file
benchmarks/warm_benchmark_opts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warm_benchmarker.dir/build.make CMakeFiles/warm_benchmarker.dir/benchmarks/warm_benchmark_opts.cpp.o
.PHONY : benchmarks/warm_benchmark_opts.cpp.o

benchmarks/warm_benchmark_opts.i: benchmarks/warm_benchmark_opts.cpp.i
.PHONY : benchmarks/warm_benchmark_opts.i

# target to preprocess a source file
benchmarks/warm_benchmark_opts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warm_benchmarker.dir/build.make CMakeFiles/warm_benchmarker.dir/benchmarks/warm_benchmark_opts.cpp.i
.PHONY : benchmarks/warm_benchmark_opts.cpp.i

benchmarks/warm_benchmark_opts.s: benchmarks/warm_benchmark_opts.cpp.s
.PHONY : benchmarks/warm_benchmark_opts.s

# target to generate assembly for a file
benchmarks/warm_benchmark_opts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/warm_benchmarker.dir/build.make CMakeFiles/warm_benchmarker.dir/benchmarks/warm_benchmark_opts.cpp.s
.PHONY : benchmarks/warm_benchmark_opts.cpp.s

examples/functions.o: examples/functions.cpp.o
.PHONY : examples/functions.o

# target to build an object file
examples/functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/functions.dir/build.make CMakeFiles/functions.dir/examples/functions.cpp.o
.PHONY : examples/functions.cpp.o

examples/functions.i: examples/functions.cpp.i
.PHONY : examples/functions.i

# target to preprocess a source file
examples/functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/functions.dir/build.make CMakeFiles/functions.dir/examples/functions.cpp.i
.PHONY : examples/functions.cpp.i

examples/functions.s: examples/functions.cpp.s
.PHONY : examples/functions.s

# target to generate assembly for a file
examples/functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/functions.dir/build.make CMakeFiles/functions.dir/examples/functions.cpp.s
.PHONY : examples/functions.cpp.s

rdmalib/lib/buffer.o: rdmalib/lib/buffer.cpp.o
.PHONY : rdmalib/lib/buffer.o

# target to build an object file
rdmalib/lib/buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/buffer.cpp.o
.PHONY : rdmalib/lib/buffer.cpp.o

rdmalib/lib/buffer.i: rdmalib/lib/buffer.cpp.i
.PHONY : rdmalib/lib/buffer.i

# target to preprocess a source file
rdmalib/lib/buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/buffer.cpp.i
.PHONY : rdmalib/lib/buffer.cpp.i

rdmalib/lib/buffer.s: rdmalib/lib/buffer.cpp.s
.PHONY : rdmalib/lib/buffer.s

# target to generate assembly for a file
rdmalib/lib/buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/buffer.cpp.s
.PHONY : rdmalib/lib/buffer.cpp.s

rdmalib/lib/connection.o: rdmalib/lib/connection.cpp.o
.PHONY : rdmalib/lib/connection.o

# target to build an object file
rdmalib/lib/connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/connection.cpp.o
.PHONY : rdmalib/lib/connection.cpp.o

rdmalib/lib/connection.i: rdmalib/lib/connection.cpp.i
.PHONY : rdmalib/lib/connection.i

# target to preprocess a source file
rdmalib/lib/connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/connection.cpp.i
.PHONY : rdmalib/lib/connection.cpp.i

rdmalib/lib/connection.s: rdmalib/lib/connection.cpp.s
.PHONY : rdmalib/lib/connection.s

# target to generate assembly for a file
rdmalib/lib/connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/connection.cpp.s
.PHONY : rdmalib/lib/connection.cpp.s

rdmalib/lib/functions.o: rdmalib/lib/functions.cpp.o
.PHONY : rdmalib/lib/functions.o

# target to build an object file
rdmalib/lib/functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/functions.cpp.o
.PHONY : rdmalib/lib/functions.cpp.o

rdmalib/lib/functions.i: rdmalib/lib/functions.cpp.i
.PHONY : rdmalib/lib/functions.i

# target to preprocess a source file
rdmalib/lib/functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/functions.cpp.i
.PHONY : rdmalib/lib/functions.cpp.i

rdmalib/lib/functions.s: rdmalib/lib/functions.cpp.s
.PHONY : rdmalib/lib/functions.s

# target to generate assembly for a file
rdmalib/lib/functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/functions.cpp.s
.PHONY : rdmalib/lib/functions.cpp.s

rdmalib/lib/rdmalib.o: rdmalib/lib/rdmalib.cpp.o
.PHONY : rdmalib/lib/rdmalib.o

# target to build an object file
rdmalib/lib/rdmalib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/rdmalib.cpp.o
.PHONY : rdmalib/lib/rdmalib.cpp.o

rdmalib/lib/rdmalib.i: rdmalib/lib/rdmalib.cpp.i
.PHONY : rdmalib/lib/rdmalib.i

# target to preprocess a source file
rdmalib/lib/rdmalib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/rdmalib.cpp.i
.PHONY : rdmalib/lib/rdmalib.cpp.i

rdmalib/lib/rdmalib.s: rdmalib/lib/rdmalib.cpp.s
.PHONY : rdmalib/lib/rdmalib.s

# target to generate assembly for a file
rdmalib/lib/rdmalib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/rdmalib.cpp.s
.PHONY : rdmalib/lib/rdmalib.cpp.s

rdmalib/lib/server.o: rdmalib/lib/server.cpp.o
.PHONY : rdmalib/lib/server.o

# target to build an object file
rdmalib/lib/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/server.cpp.o
.PHONY : rdmalib/lib/server.cpp.o

rdmalib/lib/server.i: rdmalib/lib/server.cpp.i
.PHONY : rdmalib/lib/server.i

# target to preprocess a source file
rdmalib/lib/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/server.cpp.i
.PHONY : rdmalib/lib/server.cpp.i

rdmalib/lib/server.s: rdmalib/lib/server.cpp.s
.PHONY : rdmalib/lib/server.s

# target to generate assembly for a file
rdmalib/lib/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/server.cpp.s
.PHONY : rdmalib/lib/server.cpp.s

rdmalib/lib/util.o: rdmalib/lib/util.cpp.o
.PHONY : rdmalib/lib/util.o

# target to build an object file
rdmalib/lib/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/util.cpp.o
.PHONY : rdmalib/lib/util.cpp.o

rdmalib/lib/util.i: rdmalib/lib/util.cpp.i
.PHONY : rdmalib/lib/util.i

# target to preprocess a source file
rdmalib/lib/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/util.cpp.i
.PHONY : rdmalib/lib/util.cpp.i

rdmalib/lib/util.s: rdmalib/lib/util.cpp.s
.PHONY : rdmalib/lib/util.s

# target to generate assembly for a file
rdmalib/lib/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rdmalib.dir/build.make CMakeFiles/rdmalib.dir/rdmalib/lib/util.cpp.s
.PHONY : rdmalib/lib/util.cpp.s

rfaas/lib/connection.o: rfaas/lib/connection.cpp.o
.PHONY : rfaas/lib/connection.o

# target to build an object file
rfaas/lib/connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rfaaslib.dir/build.make CMakeFiles/rfaaslib.dir/rfaas/lib/connection.cpp.o
.PHONY : rfaas/lib/connection.cpp.o

rfaas/lib/connection.i: rfaas/lib/connection.cpp.i
.PHONY : rfaas/lib/connection.i

# target to preprocess a source file
rfaas/lib/connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rfaaslib.dir/build.make CMakeFiles/rfaaslib.dir/rfaas/lib/connection.cpp.i
.PHONY : rfaas/lib/connection.cpp.i

rfaas/lib/connection.s: rfaas/lib/connection.cpp.s
.PHONY : rfaas/lib/connection.s

# target to generate assembly for a file
rfaas/lib/connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rfaaslib.dir/build.make CMakeFiles/rfaaslib.dir/rfaas/lib/connection.cpp.s
.PHONY : rfaas/lib/connection.cpp.s

rfaas/lib/devices.o: rfaas/lib/devices.cpp.o
.PHONY : rfaas/lib/devices.o

# target to build an object file
rfaas/lib/devices.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rfaaslib.dir/build.make CMakeFiles/rfaaslib.dir/rfaas/lib/devices.cpp.o
.PHONY : rfaas/lib/devices.cpp.o

rfaas/lib/devices.i: rfaas/lib/devices.cpp.i
.PHONY : rfaas/lib/devices.i

# target to preprocess a source file
rfaas/lib/devices.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rfaaslib.dir/build.make CMakeFiles/rfaaslib.dir/rfaas/lib/devices.cpp.i
.PHONY : rfaas/lib/devices.cpp.i

rfaas/lib/devices.s: rfaas/lib/devices.cpp.s
.PHONY : rfaas/lib/devices.s

# target to generate assembly for a file
rfaas/lib/devices.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rfaaslib.dir/build.make CMakeFiles/rfaaslib.dir/rfaas/lib/devices.cpp.s
.PHONY : rfaas/lib/devices.cpp.s

rfaas/lib/executor.o: rfaas/lib/executor.cpp.o
.PHONY : rfaas/lib/executor.o

# target to build an object file
rfaas/lib/executor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rfaaslib.dir/build.make CMakeFiles/rfaaslib.dir/rfaas/lib/executor.cpp.o
.PHONY : rfaas/lib/executor.cpp.o

rfaas/lib/executor.i: rfaas/lib/executor.cpp.i
.PHONY : rfaas/lib/executor.i

# target to preprocess a source file
rfaas/lib/executor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rfaaslib.dir/build.make CMakeFiles/rfaaslib.dir/rfaas/lib/executor.cpp.i
.PHONY : rfaas/lib/executor.cpp.i

rfaas/lib/executor.s: rfaas/lib/executor.cpp.s
.PHONY : rfaas/lib/executor.s

# target to generate assembly for a file
rfaas/lib/executor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rfaaslib.dir/build.make CMakeFiles/rfaaslib.dir/rfaas/lib/executor.cpp.s
.PHONY : rfaas/lib/executor.cpp.s

rfaas/lib/resources.o: rfaas/lib/resources.cpp.o
.PHONY : rfaas/lib/resources.o

# target to build an object file
rfaas/lib/resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rfaaslib.dir/build.make CMakeFiles/rfaaslib.dir/rfaas/lib/resources.cpp.o
.PHONY : rfaas/lib/resources.cpp.o

rfaas/lib/resources.i: rfaas/lib/resources.cpp.i
.PHONY : rfaas/lib/resources.i

# target to preprocess a source file
rfaas/lib/resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rfaaslib.dir/build.make CMakeFiles/rfaaslib.dir/rfaas/lib/resources.cpp.i
.PHONY : rfaas/lib/resources.cpp.i

rfaas/lib/resources.s: rfaas/lib/resources.cpp.s
.PHONY : rfaas/lib/resources.s

# target to generate assembly for a file
rfaas/lib/resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rfaaslib.dir/build.make CMakeFiles/rfaaslib.dir/rfaas/lib/resources.cpp.s
.PHONY : rfaas/lib/resources.cpp.s

server/executor/cli.o: server/executor/cli.cpp.o
.PHONY : server/executor/cli.o

# target to build an object file
server/executor/cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor.dir/build.make CMakeFiles/executor.dir/server/executor/cli.cpp.o
.PHONY : server/executor/cli.cpp.o

server/executor/cli.i: server/executor/cli.cpp.i
.PHONY : server/executor/cli.i

# target to preprocess a source file
server/executor/cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor.dir/build.make CMakeFiles/executor.dir/server/executor/cli.cpp.i
.PHONY : server/executor/cli.cpp.i

server/executor/cli.s: server/executor/cli.cpp.s
.PHONY : server/executor/cli.s

# target to generate assembly for a file
server/executor/cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor.dir/build.make CMakeFiles/executor.dir/server/executor/cli.cpp.s
.PHONY : server/executor/cli.cpp.s

server/executor/fast_executor.o: server/executor/fast_executor.cpp.o
.PHONY : server/executor/fast_executor.o

# target to build an object file
server/executor/fast_executor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor.dir/build.make CMakeFiles/executor.dir/server/executor/fast_executor.cpp.o
.PHONY : server/executor/fast_executor.cpp.o

server/executor/fast_executor.i: server/executor/fast_executor.cpp.i
.PHONY : server/executor/fast_executor.i

# target to preprocess a source file
server/executor/fast_executor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor.dir/build.make CMakeFiles/executor.dir/server/executor/fast_executor.cpp.i
.PHONY : server/executor/fast_executor.cpp.i

server/executor/fast_executor.s: server/executor/fast_executor.cpp.s
.PHONY : server/executor/fast_executor.s

# target to generate assembly for a file
server/executor/fast_executor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor.dir/build.make CMakeFiles/executor.dir/server/executor/fast_executor.cpp.s
.PHONY : server/executor/fast_executor.cpp.s

server/executor/functions.o: server/executor/functions.cpp.o
.PHONY : server/executor/functions.o

# target to build an object file
server/executor/functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor.dir/build.make CMakeFiles/executor.dir/server/executor/functions.cpp.o
.PHONY : server/executor/functions.cpp.o

server/executor/functions.i: server/executor/functions.cpp.i
.PHONY : server/executor/functions.i

# target to preprocess a source file
server/executor/functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor.dir/build.make CMakeFiles/executor.dir/server/executor/functions.cpp.i
.PHONY : server/executor/functions.cpp.i

server/executor/functions.s: server/executor/functions.cpp.s
.PHONY : server/executor/functions.s

# target to generate assembly for a file
server/executor/functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor.dir/build.make CMakeFiles/executor.dir/server/executor/functions.cpp.s
.PHONY : server/executor/functions.cpp.s

server/executor/opts.o: server/executor/opts.cpp.o
.PHONY : server/executor/opts.o

# target to build an object file
server/executor/opts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor.dir/build.make CMakeFiles/executor.dir/server/executor/opts.cpp.o
.PHONY : server/executor/opts.cpp.o

server/executor/opts.i: server/executor/opts.cpp.i
.PHONY : server/executor/opts.i

# target to preprocess a source file
server/executor/opts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor.dir/build.make CMakeFiles/executor.dir/server/executor/opts.cpp.i
.PHONY : server/executor/opts.cpp.i

server/executor/opts.s: server/executor/opts.cpp.s
.PHONY : server/executor/opts.s

# target to generate assembly for a file
server/executor/opts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor.dir/build.make CMakeFiles/executor.dir/server/executor/opts.cpp.s
.PHONY : server/executor/opts.cpp.s

server/executor_manager/cli.o: server/executor_manager/cli.cpp.o
.PHONY : server/executor_manager/cli.o

# target to build an object file
server/executor_manager/cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/cli.cpp.o
.PHONY : server/executor_manager/cli.cpp.o

server/executor_manager/cli.i: server/executor_manager/cli.cpp.i
.PHONY : server/executor_manager/cli.i

# target to preprocess a source file
server/executor_manager/cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/cli.cpp.i
.PHONY : server/executor_manager/cli.cpp.i

server/executor_manager/cli.s: server/executor_manager/cli.cpp.s
.PHONY : server/executor_manager/cli.s

# target to generate assembly for a file
server/executor_manager/cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/cli.cpp.s
.PHONY : server/executor_manager/cli.cpp.s

server/executor_manager/client.o: server/executor_manager/client.cpp.o
.PHONY : server/executor_manager/client.o

# target to build an object file
server/executor_manager/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/client.cpp.o
.PHONY : server/executor_manager/client.cpp.o

server/executor_manager/client.i: server/executor_manager/client.cpp.i
.PHONY : server/executor_manager/client.i

# target to preprocess a source file
server/executor_manager/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/client.cpp.i
.PHONY : server/executor_manager/client.cpp.i

server/executor_manager/client.s: server/executor_manager/client.cpp.s
.PHONY : server/executor_manager/client.s

# target to generate assembly for a file
server/executor_manager/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/client.cpp.s
.PHONY : server/executor_manager/client.cpp.s

server/executor_manager/executor_process.o: server/executor_manager/executor_process.cpp.o
.PHONY : server/executor_manager/executor_process.o

# target to build an object file
server/executor_manager/executor_process.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/executor_process.cpp.o
.PHONY : server/executor_manager/executor_process.cpp.o

server/executor_manager/executor_process.i: server/executor_manager/executor_process.cpp.i
.PHONY : server/executor_manager/executor_process.i

# target to preprocess a source file
server/executor_manager/executor_process.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/executor_process.cpp.i
.PHONY : server/executor_manager/executor_process.cpp.i

server/executor_manager/executor_process.s: server/executor_manager/executor_process.cpp.s
.PHONY : server/executor_manager/executor_process.s

# target to generate assembly for a file
server/executor_manager/executor_process.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/executor_process.cpp.s
.PHONY : server/executor_manager/executor_process.cpp.s

server/executor_manager/manager.o: server/executor_manager/manager.cpp.o
.PHONY : server/executor_manager/manager.o

# target to build an object file
server/executor_manager/manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/manager.cpp.o
.PHONY : server/executor_manager/manager.cpp.o

server/executor_manager/manager.i: server/executor_manager/manager.cpp.i
.PHONY : server/executor_manager/manager.i

# target to preprocess a source file
server/executor_manager/manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/manager.cpp.i
.PHONY : server/executor_manager/manager.cpp.i

server/executor_manager/manager.s: server/executor_manager/manager.cpp.s
.PHONY : server/executor_manager/manager.s

# target to generate assembly for a file
server/executor_manager/manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/manager.cpp.s
.PHONY : server/executor_manager/manager.cpp.s

server/executor_manager/opts.o: server/executor_manager/opts.cpp.o
.PHONY : server/executor_manager/opts.o

# target to build an object file
server/executor_manager/opts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/opts.cpp.o
.PHONY : server/executor_manager/opts.cpp.o

server/executor_manager/opts.i: server/executor_manager/opts.cpp.i
.PHONY : server/executor_manager/opts.i

# target to preprocess a source file
server/executor_manager/opts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/opts.cpp.i
.PHONY : server/executor_manager/opts.cpp.i

server/executor_manager/opts.s: server/executor_manager/opts.cpp.s
.PHONY : server/executor_manager/opts.s

# target to generate assembly for a file
server/executor_manager/opts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/opts.cpp.s
.PHONY : server/executor_manager/opts.cpp.s

server/executor_manager/settings.o: server/executor_manager/settings.cpp.o
.PHONY : server/executor_manager/settings.o

# target to build an object file
server/executor_manager/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/settings.cpp.o
.PHONY : server/executor_manager/settings.cpp.o

server/executor_manager/settings.i: server/executor_manager/settings.cpp.i
.PHONY : server/executor_manager/settings.i

# target to preprocess a source file
server/executor_manager/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/settings.cpp.i
.PHONY : server/executor_manager/settings.cpp.i

server/executor_manager/settings.s: server/executor_manager/settings.cpp.s
.PHONY : server/executor_manager/settings.s

# target to generate assembly for a file
server/executor_manager/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/executor_manager.dir/build.make CMakeFiles/executor_manager.dir/server/executor_manager/settings.cpp.s
.PHONY : server/executor_manager/settings.cpp.s

server/resource_manager/cli.o: server/resource_manager/cli.cpp.o
.PHONY : server/resource_manager/cli.o

# target to build an object file
server/resource_manager/cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/cli.cpp.o
.PHONY : server/resource_manager/cli.cpp.o

server/resource_manager/cli.i: server/resource_manager/cli.cpp.i
.PHONY : server/resource_manager/cli.i

# target to preprocess a source file
server/resource_manager/cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/cli.cpp.i
.PHONY : server/resource_manager/cli.cpp.i

server/resource_manager/cli.s: server/resource_manager/cli.cpp.s
.PHONY : server/resource_manager/cli.s

# target to generate assembly for a file
server/resource_manager/cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/cli.cpp.s
.PHONY : server/resource_manager/cli.cpp.s

server/resource_manager/db.o: server/resource_manager/db.cpp.o
.PHONY : server/resource_manager/db.o

# target to build an object file
server/resource_manager/db.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/db.cpp.o
.PHONY : server/resource_manager/db.cpp.o

server/resource_manager/db.i: server/resource_manager/db.cpp.i
.PHONY : server/resource_manager/db.i

# target to preprocess a source file
server/resource_manager/db.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/db.cpp.i
.PHONY : server/resource_manager/db.cpp.i

server/resource_manager/db.s: server/resource_manager/db.cpp.s
.PHONY : server/resource_manager/db.s

# target to generate assembly for a file
server/resource_manager/db.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/db.cpp.s
.PHONY : server/resource_manager/db.cpp.s

server/resource_manager/http.o: server/resource_manager/http.cpp.o
.PHONY : server/resource_manager/http.o

# target to build an object file
server/resource_manager/http.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/http.cpp.o
.PHONY : server/resource_manager/http.cpp.o

server/resource_manager/http.i: server/resource_manager/http.cpp.i
.PHONY : server/resource_manager/http.i

# target to preprocess a source file
server/resource_manager/http.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/http.cpp.i
.PHONY : server/resource_manager/http.cpp.i

server/resource_manager/http.s: server/resource_manager/http.cpp.s
.PHONY : server/resource_manager/http.s

# target to generate assembly for a file
server/resource_manager/http.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/http.cpp.s
.PHONY : server/resource_manager/http.cpp.s

server/resource_manager/manager.o: server/resource_manager/manager.cpp.o
.PHONY : server/resource_manager/manager.o

# target to build an object file
server/resource_manager/manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/manager.cpp.o
.PHONY : server/resource_manager/manager.cpp.o

server/resource_manager/manager.i: server/resource_manager/manager.cpp.i
.PHONY : server/resource_manager/manager.i

# target to preprocess a source file
server/resource_manager/manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/manager.cpp.i
.PHONY : server/resource_manager/manager.cpp.i

server/resource_manager/manager.s: server/resource_manager/manager.cpp.s
.PHONY : server/resource_manager/manager.s

# target to generate assembly for a file
server/resource_manager/manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/manager.cpp.s
.PHONY : server/resource_manager/manager.cpp.s

server/resource_manager/opts.o: server/resource_manager/opts.cpp.o
.PHONY : server/resource_manager/opts.o

# target to build an object file
server/resource_manager/opts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/opts.cpp.o
.PHONY : server/resource_manager/opts.cpp.o

server/resource_manager/opts.i: server/resource_manager/opts.cpp.i
.PHONY : server/resource_manager/opts.i

# target to preprocess a source file
server/resource_manager/opts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/opts.cpp.i
.PHONY : server/resource_manager/opts.cpp.i

server/resource_manager/opts.s: server/resource_manager/opts.cpp.s
.PHONY : server/resource_manager/opts.s

# target to generate assembly for a file
server/resource_manager/opts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/opts.cpp.s
.PHONY : server/resource_manager/opts.cpp.s

server/resource_manager/settings.o: server/resource_manager/settings.cpp.o
.PHONY : server/resource_manager/settings.o

# target to build an object file
server/resource_manager/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/settings.cpp.o
.PHONY : server/resource_manager/settings.cpp.o

server/resource_manager/settings.i: server/resource_manager/settings.cpp.i
.PHONY : server/resource_manager/settings.i

# target to preprocess a source file
server/resource_manager/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/settings.cpp.i
.PHONY : server/resource_manager/settings.cpp.i

server/resource_manager/settings.s: server/resource_manager/settings.cpp.s
.PHONY : server/resource_manager/settings.s

# target to generate assembly for a file
server/resource_manager/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/resource_manager.dir/build.make CMakeFiles/resource_manager.dir/server/resource_manager/settings.cpp.s
.PHONY : server/resource_manager/settings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... benchmarks"
	@echo "... cold_benchmarker"
	@echo "... cpp_interface"
	@echo "... executor"
	@echo "... executor_manager"
	@echo "... functions"
	@echo "... parallel_invocations"
	@echo "... rdmalib"
	@echo "... resource_manager"
	@echo "... rfaaslib"
	@echo "... spdlog"
	@echo "... warm_benchmarker"
	@echo "... benchmarks/cold_benchmark.o"
	@echo "... benchmarks/cold_benchmark.i"
	@echo "... benchmarks/cold_benchmark.s"
	@echo "... benchmarks/cold_benchmark_opts.o"
	@echo "... benchmarks/cold_benchmark_opts.i"
	@echo "... benchmarks/cold_benchmark_opts.s"
	@echo "... benchmarks/cpp_interface.o"
	@echo "... benchmarks/cpp_interface.i"
	@echo "... benchmarks/cpp_interface.s"
	@echo "... benchmarks/cpp_interface_opts.o"
	@echo "... benchmarks/cpp_interface_opts.i"
	@echo "... benchmarks/cpp_interface_opts.s"
	@echo "... benchmarks/parallel_invocations.o"
	@echo "... benchmarks/parallel_invocations.i"
	@echo "... benchmarks/parallel_invocations.s"
	@echo "... benchmarks/parallel_invocations_opts.o"
	@echo "... benchmarks/parallel_invocations_opts.i"
	@echo "... benchmarks/parallel_invocations_opts.s"
	@echo "... benchmarks/settings.o"
	@echo "... benchmarks/settings.i"
	@echo "... benchmarks/settings.s"
	@echo "... benchmarks/warm_benchmark.o"
	@echo "... benchmarks/warm_benchmark.i"
	@echo "... benchmarks/warm_benchmark.s"
	@echo "... benchmarks/warm_benchmark_opts.o"
	@echo "... benchmarks/warm_benchmark_opts.i"
	@echo "... benchmarks/warm_benchmark_opts.s"
	@echo "... examples/functions.o"
	@echo "... examples/functions.i"
	@echo "... examples/functions.s"
	@echo "... rdmalib/lib/buffer.o"
	@echo "... rdmalib/lib/buffer.i"
	@echo "... rdmalib/lib/buffer.s"
	@echo "... rdmalib/lib/connection.o"
	@echo "... rdmalib/lib/connection.i"
	@echo "... rdmalib/lib/connection.s"
	@echo "... rdmalib/lib/functions.o"
	@echo "... rdmalib/lib/functions.i"
	@echo "... rdmalib/lib/functions.s"
	@echo "... rdmalib/lib/rdmalib.o"
	@echo "... rdmalib/lib/rdmalib.i"
	@echo "... rdmalib/lib/rdmalib.s"
	@echo "... rdmalib/lib/server.o"
	@echo "... rdmalib/lib/server.i"
	@echo "... rdmalib/lib/server.s"
	@echo "... rdmalib/lib/util.o"
	@echo "... rdmalib/lib/util.i"
	@echo "... rdmalib/lib/util.s"
	@echo "... rfaas/lib/connection.o"
	@echo "... rfaas/lib/connection.i"
	@echo "... rfaas/lib/connection.s"
	@echo "... rfaas/lib/devices.o"
	@echo "... rfaas/lib/devices.i"
	@echo "... rfaas/lib/devices.s"
	@echo "... rfaas/lib/executor.o"
	@echo "... rfaas/lib/executor.i"
	@echo "... rfaas/lib/executor.s"
	@echo "... rfaas/lib/resources.o"
	@echo "... rfaas/lib/resources.i"
	@echo "... rfaas/lib/resources.s"
	@echo "... server/executor/cli.o"
	@echo "... server/executor/cli.i"
	@echo "... server/executor/cli.s"
	@echo "... server/executor/fast_executor.o"
	@echo "... server/executor/fast_executor.i"
	@echo "... server/executor/fast_executor.s"
	@echo "... server/executor/functions.o"
	@echo "... server/executor/functions.i"
	@echo "... server/executor/functions.s"
	@echo "... server/executor/opts.o"
	@echo "... server/executor/opts.i"
	@echo "... server/executor/opts.s"
	@echo "... server/executor_manager/cli.o"
	@echo "... server/executor_manager/cli.i"
	@echo "... server/executor_manager/cli.s"
	@echo "... server/executor_manager/client.o"
	@echo "... server/executor_manager/client.i"
	@echo "... server/executor_manager/client.s"
	@echo "... server/executor_manager/executor_process.o"
	@echo "... server/executor_manager/executor_process.i"
	@echo "... server/executor_manager/executor_process.s"
	@echo "... server/executor_manager/manager.o"
	@echo "... server/executor_manager/manager.i"
	@echo "... server/executor_manager/manager.s"
	@echo "... server/executor_manager/opts.o"
	@echo "... server/executor_manager/opts.i"
	@echo "... server/executor_manager/opts.s"
	@echo "... server/executor_manager/settings.o"
	@echo "... server/executor_manager/settings.i"
	@echo "... server/executor_manager/settings.s"
	@echo "... server/resource_manager/cli.o"
	@echo "... server/resource_manager/cli.i"
	@echo "... server/resource_manager/cli.s"
	@echo "... server/resource_manager/db.o"
	@echo "... server/resource_manager/db.i"
	@echo "... server/resource_manager/db.s"
	@echo "... server/resource_manager/http.o"
	@echo "... server/resource_manager/http.i"
	@echo "... server/resource_manager/http.s"
	@echo "... server/resource_manager/manager.o"
	@echo "... server/resource_manager/manager.i"
	@echo "... server/resource_manager/manager.s"
	@echo "... server/resource_manager/opts.o"
	@echo "... server/resource_manager/opts.i"
	@echo "... server/resource_manager/opts.s"
	@echo "... server/resource_manager/settings.o"
	@echo "... server/resource_manager/settings.i"
	@echo "... server/resource_manager/settings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

